//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Weiya2025.Assets
{
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n()
        {
        }

        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weiya2025.Assets.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        #region 字典集
        /*關鍵字命名規則 :
         * 
         * - UI
         *   - label_xxx  : 表單文字, 固定文字, 等
         *   - btn_xxx     : 按鈕類
         *   - menu_xxx : 工具列選項
         *   - hint_xxx    : 類似於 tooltips 文字
         * 
         * - 後端訊息
         *   - info_xxx         : 一般訊息
         *   - success_xxx  : 成功訊息
         *   - warning_xxx : 警告訊息
         *   - error_xxx       : 錯誤訊息
         *   - wait_xxx         : 等候訊息
         *   - ask_xxx           : 詢問訊息
         *   - http_400_xxx : API bad request
         *   - http_401_xxx : API unauth
         *   - http_403_xxx : API forbidden
         *   - http_500_xxx : API internal server error
         *   - http_503_xxx : API request model error (大概率)
         */

        /// <summary>
        /// Demo 用 current_language
        /// </summary>
        public static string current_language { get => ResourceManager.GetString("current_language", Culture); }

        #region AuthVerifyModal
        /// <summary>
        /// 身分驗證
        /// </summary>
        public static string label_form_auth_verify_modal_title { get => ResourceManager.GetString("label_form_auth_verify_modal_title", Culture); }
        /// <summary>
        /// 帳號
        /// </summary>
        public static string label_signin_account { get => ResourceManager.GetString("label_signin_account", Culture); }
        /// <summary>
        /// 密碼
        /// </summary>
        public static string label_signin_password { get => ResourceManager.GetString("label_signin_password", Culture); }

        /// <summary>
        /// 登入
        /// </summary>
        public static string btn_singin { get => ResourceManager.GetString("btn_singin", Culture); }
        /// <summary>
        /// 使用本機帳號登入
        /// </summary>
        public static string btn_signin_with_ad { get => ResourceManager.GetString("btn_signin_with_ad", Culture); }
        /// <summary>
        /// 離開本應用程式
        /// </summary>
        public static string btn_leave_app { get => ResourceManager.GetString("btn_leave_app", Culture); }

        /// <summary>
        /// 登入中, 請稍後 ...
        /// </summary>
        public static string wait_signin { get => ResourceManager.GetString("wait_signin", Culture); }

        /// <summary>
        /// 登入失敗
        /// </summary>
        public static string error_signin { get => ResourceManager.GetString("error_signin", Culture); }
        /// <summary>
        /// 帳號不可為空
        /// </summary>
        public static string error_signin_empty_account { get => ResourceManager.GetString("error_signin_empty_account", Culture); }
        /// <summary>
        /// 密碼不可為空
        /// </summary>
        public static string error_signin_empty_password { get => ResourceManager.GetString("error_signin_empty_password", Culture); }
        /// <summary>
        /// 無法取得身分交換權杖
        /// </summary>
        public static string error_no_challenge_code { get => ResourceManager.GetString("error_no_challenge_code", Culture); }
        /// <summary>
        /// 無法取得身分權杖
        /// </summary>
        public static string error_no_access_token { get => ResourceManager.GetString("error_no_access_token", Culture); }
        /// <summary>
        /// 授權失敗
        /// </summary>
        public static string error_auth { get => ResourceManager.GetString("error_auth", Culture); }
        /// <summary>
        /// 身分權杖已逾時
        /// </summary>
        public static string error_token_expired { get => ResourceManager.GetString("error_token_expired", Culture); }
        /// <summary>
        /// 授權申請失敗
        /// </summary>
        public static string error_auth_apply { get => ResourceManager.GetString("error_auth_apply", Culture); }


        /// <summary>
        /// 授權申請單
        /// </summary>
        public static string info_auth_application { get => ResourceManager.GetString("info_auth_application", Culture); }
        /// <summary>
        /// 授權申請通過後即可重新登入, 如果有緊急需要 可以直撥分機 #2572
        /// </summary>
        public static string info_success_auth_apply { get => ResourceManager.GetString("info_success_auth_apply", Culture); }

        /// <summary>
        /// 歡迎回來
        /// </summary>
        public static string success_signin { get => ResourceManager.GetString("success_signin", Culture); }
        /// <summary>
        /// 授權申請成功
        /// </summary>
        public static string success_auth_apply { get => ResourceManager.GetString("success_auth_apply", Culture); }

        /// <summary>
        /// 正在為您轉跳至授權申請單 ...
        /// </summary>
        public static string warn_redirect_auth_application { get => ResourceManager.GetString("warn_redirect_auth_application", Culture); }

        /// <summary>
        /// 您是否要向服務擁有者申請授權 ??
        /// </summary>
        public static string ask_auth_application { get => ResourceManager.GetString("ask_auth_application", Culture); }

        #endregion AuthVerifyModal

        #region Common
        /// <summary>
        /// 請直接聯繫開發人員 直撥分機 #2572
        /// </summary>
        public static string error_contact_developer { get => ResourceManager.GetString("error_contact_developer", Culture); }
        /// <summary>
        /// 系統錯誤, 請聯絡開發人員
        /// </summary>
        public static string error_other { get => ResourceManager.GetString("error_other", Culture); }

        /// <summary>
        /// 身分驗證錯誤
        /// </summary>
        public static string http_401 { get => ResourceManager.GetString("http_401", Culture); }
        /// <summary>
        /// 權限不足
        /// </summary>
        public static string http_403 { get => ResourceManager.GetString("http_403", Culture); }
        /// <summary>
        /// 內部發生錯誤, 請聯絡開發人員
        /// </summary>
        public static string http_500 { get => ResourceManager.GetString("http_500", Culture); }

        /// <summary>
        /// 作業中
        /// </summary>
        public static string wait_processing { get => ResourceManager.GetString("wait_processing", Culture); }
        /// <summary>
        /// 請稍後 ...
        /// </summary>
        public static string wait_waiting { get => ResourceManager.GetString("wait_waiting", Culture); }

        #endregion Common

        #endregion 字典集
    }
}
